In [ ]:
#CHI Square Test is applied when we have 2 categorical variables from the same 
#population. It is used to determine whether there is significant association
#between them  

In [ ]:
#Here H0: X AND Y ARE INDEPENDENT / UNASSOCIATED
#H1: X AND Y ARE DEPENDENT /ASSOCIATED

In [1]:
import scipy.stats as stats
import pandas as pd
import numpy as np
import seaborn as sns
from scipy.stats import chi2
dataset=sns.load_dataset('tips')

In [3]:
dataset

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [2]:
#Cross Tabulation --> Contingency Table between Smoker & Sex
dataset_table=pd.crosstab(dataset['sex'],dataset['smoker'])
dataset_table

smoker  Yes  No
sex            
Male     60  97
Female   33  54

In [3]:
observed_values=dataset_table.values
observed_values

array([[60, 97],
       [33, 54]], dtype=int64)

In [4]:
#Expected Value under Null Hypothesis
#Expected Value = (Row total* Column total)/ Grand Total
val=stats.chi2_contingency(dataset_table)
val

(0.008763290531773594, 0.925417020494423, 1, array([[59.84016393, 97.15983607],
        [33.15983607, 53.84016393]]))

In [5]:
Expected_value=val[3]
Expected_value

array([[59.84016393, 97.15983607],
       [33.15983607, 53.84016393]])

In [20]:
no_of_rows=len(dataset_table.iloc[0:2,0]) #Row Index, Column Index
no_of_rows

2

In [ ]:
no_of_cols=len(dataset_table.iloc[0,0:2]) #Row Index, Column Index
ddof=(no_of_rows-1)*(no_of_cols-1)
ddof

In [9]:
alpha=0.05

In [11]:
#Calc Chi square statistic
#((Observed-Expected)**2)/Expected 
#And Add respective chi sqaure values

chi_square=sum([(o-e)**2/e for o,e in zip(observed_values,Expected_value)])
chi_square

array([0.00119737, 0.00073745])

In [13]:
#Add
chi_square_statistic=chi_square[0]+chi_square[1]
chi_square_statistic

0.001934818536627623

In [21]:
#critical_value=chi2.ppf(q=1-alpha,df=ddof)
#critical_value

3.841458820694124

In [16]:
#p value 
#cdf --> Cumulative Distribution Function
p_value=1-chi2.cdf(x=chi_square_statistic,df=ddof)
p_value

0.964915107315732

In [15]:
if p_value < 0.05:
    print('Reject Null Hypotesis')
else:
    print('Fail to reject Null Hypothesis') # x and y are independent 
    #(unassociated)

Fail to reject Null Hypothesis


In [34]:
#if chi_square_statistic > critical_value:
    #print('Reject HO')
#else:
    #print('Fail to reject H0')

Fail to reject H0
